import { useEffect, useState } from "react";
import { fetchRiderDeliveries, updateDeliveryStatus } from "../api";
import { DeliveryRequest, DeliveryStatus } from "../types";

const RIDER_ID = "rider-demo-1";
const STEPS: DeliveryStatus[] = ["ASSIGNED", "PICKED_UP", "IN_TRANSIT", "ARRIVED", "DELIVERED"];

export default function RiderScreen() {
    const [deliveries, setDeliveries] = useState<DeliveryRequest[]>([]); const [loading, setLoading] = useState(true); const [scanTarget, setScanTarget] = useState<string|null>(null); const [scanInput, setScanInput] = useState(""); const [error, setError] = useState<string|null>(null);
    const load = async () => { try { const data = await fetchRiderDeliveries(RIDER_ID); setDeliveries(data.filter(d => d.status !== "DELIVERED")); } catch {} finally { setLoading(false); } };
    useEffect(() => { load(); }, []);
    const advance = async (d: DeliveryRequest) => { const next: Record<string, DeliveryStatus> = { ASSIGNED:"PICKED_UP", PICKED_UP:"IN_TRANSIT", IN_TRANSIT:"ARRIVED", ARRIVED:"DELIVERED" }; const status = next[d.status]; if (!status) return; if (status === "DELIVERED") { setScanTarget(d.id); return; } await updateDeliveryStatus(d.id, status as "PICKED_UP" | "DELIVERED"); load(); };
    const confirm = async (id:string) => { setError(null); try { await updateDeliveryStatus(id,"DELIVERED",scanInput); setScanTarget(null); setScanInput(""); load(); } catch(e:any){setError(e.message ?? "The QR code could not be verified.");} };

    return <section className="screen-modern"><div className="page-heading"><div><span className="eyebrow">RIDER APP</span><h1>Ready when you are.</h1><p>Your route, your next action, and delivery proof — all in one place.</p></div><div className="rider-status-chip"><span /> ON DUTY</div></div>
        {loading ? <div className="panel loading-panel">Loading your route…</div> : deliveries.length === 0 ? <div className="panel empty-modern"><div className="empty-icon">⌁</div><h3>No active deliveries</h3><p>You're all clear. New assignments will appear here.</p></div> : <div className="rider-delivery-list">{deliveries.map(d => { const idx = Math.max(0, STEPS.indexOf(d.status)); return <div className="panel rider-delivery" key={d.id}><div className="delivery-top"><div><span className="eyebrow">ACTIVE DELIVERY · #{d.id.slice(-5)}</span><h3>{d.customerName}</h3><p>{d.address}</p></div><span className={`status-pill status-${d.status}`}>{d.status.replace("_"," ")}</span></div><div className="progress-steps">{STEPS.map((s,i)=><div className={`progress-step ${i<=idx?"done":""} ${i===idx?"current":""}`} key={s}><div className="step-dot">{i<idx?"✓":i+1}</div><span>{s.replace("_"," ")}</span></div>)}</div><div className="delivery-details"><div><small>PACKAGE</small><strong>{d.itemDescription}</strong></div><div><small>DESTINATION</small><strong>{d.address}</strong></div></div>{scanTarget === d.id ? <div className="verify-box"><span className="verify-icon">⌗</span><div><strong>Verify delivery</strong><p>Scan the customer's QR code to complete this order.</p><input value={scanInput} onChange={e=>setScanInput(e.target.value)} placeholder="Scanned code" autoFocus />{error&&<p className="error-text">{error}</p>}<div className="verify-actions"><button className="secondary-btn" onClick={()=>setScanTarget(null)}>Cancel</button><button className="primary-btn compact" disabled={!scanInput} onClick={()=>confirm(d.id)}>Confirm delivery</button></div></div></div> : <button className="primary-btn" onClick={()=>advance(d)}>{d.status === "ARRIVED" ? "Scan QR & complete" : d.status === "ASSIGNED" ? "Accept & pick up" : d.status === "PICKED_UP" ? "Start delivery" : "Mark as arrived"}<span>→</span></button>}</div>})}</div>}
    </section>;
}
