import { useEffect, useState } from "react";

const statuses = ["ASSIGNED", "PICKED UP", "IN TRANSIT", "ARRIVED", "DELIVERED"];

export default function TrackingScreen() {
    const [active, setActive] = useState(2);
    useEffect(() => { const i=setInterval(()=>setActive(v=>v<3?v+1:v), 7000); return ()=>clearInterval(i); }, []);
    return <div className="tracking-page"><header className="tracking-nav"><div className="brand"><div className="brand-mark">R</div><div><div className="brand-name">reflex</div><div className="brand-tag">live delivery</div></div></div><div className="secure-label">● LIVE TRACKING</div></header><main className="tracking-main"><div className="tracking-copy"><span className="eyebrow">DELIVERY RX1024</span><h1>Your order is on the way.</h1><p>Follow your rider in real time. No app or account required.</p></div><div className="tracking-grid"><section className="tracking-map-card"><div className="big-map"><div className="map-grid"/><div className="map-neighborhood n1">WESTLANDS</div><div className="map-neighborhood n2">KILIMANI</div><div className="map-neighborhood n3">PARKLANDS</div><div className="big-route"/><div className="map-stop start">R</div><div className="rider-live"><span>R</span><i /></div><div className="map-stop end">●</div><div className="map-card-label"><span className="pulse"/> Rider location updates live</div></div></section><aside className="tracking-info"><div className="arrival-card"><span className="eyebrow">ESTIMATED ARRIVAL</span><strong>{active >= 3 ? "Arrived" : "12 min"}</strong><span>{active >= 3 ? "Your rider is at the destination" : "Traffic looks clear"}</span></div><div className="rider-profile"><div className="large-avatar">BK</div><div><small>YOUR RIDER</small><h3>Brian Kamau</h3><p>Reflex rider · ★ 4.9</p></div><button aria-label="Call rider">☎</button></div><div className="timeline">{statuses.map((s,i)=><div className={`timeline-item ${i<=active?"complete":""} ${i===active?"now":""}`} key={s}><div className="timeline-dot">{i<active?"✓":i===active?"•":""}</div><div><strong>{s}</strong><small>{i===active ? (s === "IN TRANSIT" ? "Rider is heading to you" : "Current status") : i<active ? "Completed" : "Up next"}</small></div></div>)}</div><div className="tracking-help">Need help? <strong>Contact the retailer</strong></div></aside></div></main></div>;
}
